### ISSUE TITLE
Need Help to Run the Program

### ISSUE THREAD

**Issue by White-Pirate** [catcathh/UltraPixel#21]
Hello,

I have installed everything, but I’m not sure how to run the program. Could you please guide me on where and how to start it? Any advice would be greatly appreciated.

I apologize if this question is not appropriate for this section, I’m new to GitHub.

Thank you in advance!

![image](https://github.com/user-attachments/assets/8b5f813a-3e3c-4111-bc5e-b9a8126f73ff)
![image](https://github.com/user-attachments/assets/a4064beb-4a8e-4409-bb2b-9efc911069d2)

**Comment by catcathh** [comment]
Thanks for your interest.
From the image you provided, it appears that you are using a Windows operating system. Currently, our code is only designed to run on Linux, so we are unable to provide more insights regarding running it on Windows. However, you can try using this online demo instead (https://huggingface.co/spaces/roubaofeipi/UltraPixel-demo)

**Comment by White-Pirate** [comment]
> Thanks for your interest. From the image you provided, it appears that you are using a Windows operating system. Currently, our code is only designed to run on Linux, so we are unable to provide more insights regarding running it on Windows. However, you can try using this online demo instead (https://huggingface.co/spaces/roubaofeipi/UltraPixel-demo)

Thank you for your response and clarification. I appreciate your help!
