### ISSUE TITLE
Other SD versions support?

### ISSUE THREAD

**Issue by andupotorac** [catcathh/UltraPixel#4]
Hi. On page 15 you showcase results for SDXL. Is it fair to assume the code would work on other versions of SD?

**Comment by catcathh** [comment]
The figure on page 15 primarily compares the latent space differences between StableCascade and SDXL. The latent space of StableCascade is more compact. Currently, our method only supports StableCascade. We are not certain if it can be applied to other SD models, as their latent spaces are not as compact as StableCascade's. This might result in significantly higher training costs.

**Comment by andupotorac** [comment]
Got it, thanks!
